Dropdown menus
Epic-Institute/positive-disruption pull request #99
Opened 2023-05-09 21:32 UTC by fbecerra-epic

2023-05-09 21:35 UTC, fbecerra-epic commented on podi/app.py
> +for level in index_names[:-2]:
This is a very hacky way of iterating over df.index.names, which is not available outside the function. @nadams-ei what's the difference between df.index.names and index_names? Do you know a smart way of accessing the elements that are used to add dropdown menus (which seems to be df.index.names) from this part of the code? Should we create another variable to store them?

2023-05-10 11:28 UTC, fbecerra-epic commented on podi/app.py
> +for level in all_possible_index_values[:-3]:
This got moved by the merge with main, but the comment still applies:

This is a very hacky way of iterating over df.index.names, which is not available outside the function. @nadams-ei what's the difference between df.index.names and index_names? Do you know a smart way of accessing the elements that are used to add dropdown menus (which seems to be df.index.names) from this part of the code? Should we create another variable to store them?

2023-05-10 15:42 UTC, nadams-ei requested changes

2023-05-10 15:42 UTC, nadams-ei commented on podi/app.py
> +for level in all_possible_index_values[:-3]:
all_possible_index_values (which probably should instead be called all_possible_index_names) lists all index names for all model_output options (energy, emissions, concentration, etc.)

df.index.names is a subset of all_possible_index_values, determined by:
1. The choice of model_output (energy, emissions, etc.)
2. The choice of index names for which we want to offer dropdowns (to keep the number of dropdowns reasonably small). This is defined by data_controls_dropdowns.

I don't currently know of a good way to access df.index.names from this part of the code; it seems possible but I'm still  sorting it out, because it will also help with the update_data_controls function I'm working on directly above.

If you see a way to create another variable to store these elements then feel free to give that a try.

2023-05-10 15:42 UTC, nadams-ei commented on podi/app.py
> +for level in all_possible_index_values[:-3]:
These new dropdowns are looking great! The Flow select/deselect all is not working though.

2023-05-16 19:12 UTC, fbecerra-epic commented on podi/app.py
> +for level in all_possible_index_values[:-3]:
@nadams-ei it seems that the only dropdown that is not working is "flow". Since all the other dropdowns are working fine, this might be an issue somewhere else in the code. Do you have an idea of what might be going on?

2023-05-16 20:17 UTC, fbecerra-epic commented on podi/app.py
> +for level in all_possible_index_values[:-3]:
I checked out the main branch and realized that this bug is also present there. When you clear the selection for "flow", the graph doesn't update. So this is not a bug of this branch, but a bug in the main branch.

2023-05-17 12:06 UTC, fbecerra-epic commented
@nadams-ei the selecting/deselecting flow problem is a bug in the main branch of the code, not this PR. Hence, I went ahead and requested your review again. The flow bug will have to be addressed in a different branch and PR.

2023-05-17 15:53 UTC, merged